from pytoonz import *

track1 = Track('Morph', 'Twenty One Pilots')
track2 = Track('Jumpsuit', "Twenty One Pilots")
track3 = Track('Car Radio', 'Twenty One Pilots')
track4 = Track('Trees', 'Twenty One Pilots')
track5 = Track('Blasphemy', 'Twenty One Pilots')
track6 = Track('The Judge','Twenty One Pilots')
track7 = Track('Not Today','Twenty One Pilots')
track8 = Track('Bandito', "Twenty One Pilots")
track9 = Track('Chlorine','Twenty One Pilots')

playlist = PyToonz()

for i in [track1,track2,track3,track4,track5,track6,track7,track8,track9]:
    playlist.add_track(i)
print(playlist)
print("\n=============================")
print("remove tracks 1,5,7")
playlist.remove_current()
playlist.next_track()
playlist.next_track()
playlist.next_track()
playlist.remove_current()
playlist.next_track()
playlist.remove_current()
print(playlist)
print("\n=============================")
playlist.reset()
print(playlist)
print("\n=============================")
print("add blasphemy to pos 2, Not today to end")
playlist.add_after(track5)
playlist.add_track(track7)
print(playlist)
print("\n=============================")
print("remove first,last")
playlist.remove_current()
playlist.prev_track()
playlist.remove_current()
print(playlist)
playlist.play()
playlist.remove_current()
playlist.add_track(track5)
print(playlist)
